version: 2
updates:
- package-ecosystem: uv
  directories:
    - "/"
  exclude-paths:
    - "oldest/*"
  schedule:
    interval: daily
    time: "02:10"
  open-pull-requests-limit: 1
  cooldown:
    default-days: 7
  commit-message:
    prefix: " "
- package-ecosystem: github-actions
  directories:
  - "/"
  - "/.github/actions/*"
  schedule:
    interval: daily
    time: "03:10"
  open-pull-requests-limit: 1
  cooldown:
    default-days: 7
  groups:
    fizyk-actions-reuse:
      patterns:
      - "fizyk/actions-reuse/*"
    checkout:
      patterns:
      - "actions/checkout"
    setup-postgres:
      patterns:
      - "ankane/setup-postgres"
  commit-message:
    prefix: " "
- package-ecosystem: pre-commit
  directory: "/"
  schedule:
    interval: daily
    time: "04:10"
  open-pull-requests-limit: 1
  cooldown:
    default-days: 7
