name: Test build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

permissions: {}

jobs:
  build:
    permissions:
      contents: read  # actions/checkout in the reusable workflow
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@5e3ff7b4d544d6b3b8336cdc9c029cff9ab7abb3 # v5.2.7
    with:
      dependency-manager: uv
