name: Render Mermaid Diagrams
on:
  push:
    paths:
      - 'docs/*.mmd' # Trigger only when mermaid files change

jobs:
  render:
    # Grant the action permission to write to the repository
    permissions:
      contents: write
    uses: fizyk/actions-reuse/.github/workflows/shared-diagram.yml@c76d10cf9448b3a9afdbef29e727e0fd00b2f544 # v5.2.8
