name: Render Mermaid Diagrams
on:
  push:
    paths:
      - 'docs/*.mmd' # Trigger only when mermaid files change

jobs:
  render:
    # Grant the action permission to write to the repository
    permissions:
      contents: write
    uses: fizyk/actions-reuse/.github/workflows/shared-diagram.yml@9328bd2621a0322c2d7aeb80cd41f53a8771f4ee # v5.2.5
